### ISSUE TITLE
datatables pagination is LTR

### ISSUE THREAD

**Issue by mamal72** [magnagroup/sb-admin-2-persian#2]
The pagination of datatables in the demo is LTR. I could fix it and send a PR but it was in the Bootstrap's default. I could fix it in the main.less file or somewhere else but...
I did not check the minified Bootstrap file that you are using but I think it's the normal LTR Bootstrap. Isn't it better to use [bootstrap-rtl](https://github.com/morteza/bootstrap-rtl)? As you may know, in any Persian or RTL project, we may need a lot more components of Bootstrap. So it could be good to use a RTL version here too in order to avoid future problems. :+1:

**Comment by m-jch** [comment]
Thanks, Using bootstrap-rtl is a better solution, I try to to use this in the near future.

**Comment by mamal72** [comment]
Thanks! :+1:
